### ISSUE TITLE
Migrate the build process to sbt

### ISSUE THREAD

**Issue by folone** [typelevel/scala#35]
Would be great to have this fork built via sbt (use work done by @paulp in his fork https://github.com/paulp/policy/commit/78558b066d187f5e18d98515724c3495029c59f1 ?).

**Comment by puffnfresh** [comment]
:+1:

**Comment by fommil** [comment]
or maker https://github.com/cage433/maker

**Comment by paulp** [comment]
@fommil Oh I didn't know about this. Though I have invested a borderline-insane amount of time into sbt at this point, I don't subscribe to the sunk cost fallacy (with sbt that is - I seem to swallow it hook line and sinker with scala - anyway) and nothing would make me happier than burning sbt to the ground. I am initially skeptical, because build tools are the classic application where nobody uses more than X% of the features but everyone uses a different X%. I'll look at it.

**Comment by paulp** [comment]
Okay I'm back. Nope.

**Comment by fommil** [comment]
@paulp we use it at work, so it's industry hardened for performance on very large projects. Have a look at my wishlist in the issue tracker to see what needs to happen before it can be used more generally for OSS projects: not too much work actually. It's a **lot** easier to extend than sbt.

**Comment by paulp** [comment]
If I was going to pull back that far I'd pull back all the way, because something like sbt only less impossible to understand is not what I want. I don't want arbitrary logic appearing at every imaginable place in the build. scala is overpowered for most normal programming tasks, and that's 10x as true in the build. I'm pretty close to molding sbt into such a system so that sbt is a black box and the build is controlled via configuration. If there is motivation I could make a lateral move someday.

**Comment by milessabin** [comment]
These aren't mutually exclusive options. @fommil if you want to work on a maker build for Scala then just go ahead and do it. If it has obvious advantages over the Ant and SBT builds then people are more likely to be persuaded to adopt it.

**Comment by fommil** [comment]
I'll send an unsolicited PR when it's ready (some work to do on maker first to make it publicly usable)

**Comment by paulp** [comment]
If you want to investigate taking advantage of my build code, both policy and psp-std now have the majority of their build code in [libsbt](https://github.com/paulp/psp-libsbt).

However I'm concerned by @puffnfresh's comment elsewhere which seemed to me to grossly underestimate how much work is involved. There's a reason that after multiple abandoned attempts, scala itself still has no sbt build. I have put an ungodly amount of time into sbt-related fiddling, especially when I have to go outside the normal sbt box, which is often. If you want this code to be usable in projects which aren't mine, I will have to see some real help, because otherwise I have zero motivation to make it any more general than I need.

**Comment by puffnfresh** [comment]
@paulp I don't have any idea what work needs to be done. I would like to help.

**Comment by paulp** [comment]
If you familiarize yourself with the contents of policy/project and libsbt in its entirety, the ways in which it won't just drop into the scala build will become apparent. I can elaborate over time.

The concrete thing I could use the most help with is tests.

**Comment by gkossakowski** [comment]
Hi,

The scala/scala repo would like to enjoy sbt build too. Right off the top of my head, here are the reasons for scala/scala not having sbt build yet:
- bootstrapping is difficult; Scala builds itself with Scala (some previous version), no other project is like that
- incremental compilation used to end up rebuilding most of your code base; people would prefer naive Ant's incremental compilation over poor performance
- there's a ton of projects and infrastructure (e.g. our release process) that assumes antism and not sbtism in scala/scala

Our bootstrapping process is becoming more and more streamlined. First of all, we moved to use released version of Scala as starr instead of arbitrary snapshots. Next on the list is getting rid of locker step: it's already optional and that optionality is exercised by PR validator to provide faster feedback on pull requests. There were some fixes to how `scalaInstance` is handled internally by sbt to make Scala building Scala less of an aberration.

Incremental compiler has [learnt](https://github.com/sbt/sbt/blob/0.13/compile/inc/src/main/scala/sbt/inc/IncOptions.scala#L83) how to behave like Ant. With little refactoring of Scala's compiler cake, we should be able to move to just using name hashing and have proper incremental compilation.

Infrastructure will just need work to adopt to sbt build.

Given that upstream would like to have an sbt build too, would you guys be interested in working on it together there?

**Comment by SethTisue** [comment]
a great deal of progress on this has already been made in the main scala/scala repo, and I (& the rest of the team at Typesafe) intend to finish it off. the list of remaining blockers is shorter than ever. (and the temperature in hell, I'm told, does occasionally dip below 0ºC)

**Comment by paulp** [comment]
![wry commentary](https://cloud.githubusercontent.com/assets/9135/9778560/e3934160-5726-11e5-85b2-cf7b2585ce48.jpg)

**Comment by SethTisue** [comment]
<img src="http://stream1.gifsoup.com/view6/4592305/lemmings-off-the-cliff-o.gif">

**Comment by folone** [comment]
Right, after #97 we're actually using what's in the main scala repo. Closing :rotating_light:
