### ISSUE TITLE
Add support for typed holes

### ISSUE THREAD

**Issue by milessabin** [typelevel/scala#37]
As seen in [GHC](http://www.haskell.org/haskellwiki/GHC/Typed_holes) and Agda

**Comment by relrod** [comment]
:+1:!

**Comment by puffnfresh** [comment]
Oh hell yeah :+1: 

I tried doing this with @djspiewak as a def macro but it didn't provide enough context. The compiler definitely will.

**Comment by djspiewak** [comment]
I still think you gave up too easily… ;-)

This is going to be awesome.

**Comment by folone** [comment]
That would be so cool!

**Comment by Blaisorblade** [comment]
:+1: Sometimes Agda is more productive than Scala because of this (and of completion, in fairness).

BTW, see also http://dl.acm.org/citation.cfm?id=2462192 "Complete completion using types and weights" for the completion part.
I can get through the paywall for free if you need copies of the paper (not so for Springer though).

**Comment by Blaisorblade** [comment]
@puffnfresh ready? Where can we see it :-) ?
EDIT: sorry, I realized that "ready" means "the feature design is ready", nothing more.

**Comment by milessabin** [comment]
@Blaisorblade "ready" means "ready to be worked on".

**Comment by propensive** [comment]
Can we change the name "ready" to something else? It caught me out again
​last week when I was chatting to Lars and I thought an issue with the
"ready" label had been mistagged...

Not sure if it's even possible to do, but "specified"?

Jon

**Comment by milessabin** [comment]
"Ready" is pretty standard Kanban terminology ... I think we should leave it as it is.

**Comment by Blaisorblade** [comment]
@propensive: +1

> "Ready" is pretty standard Kanban terminology ... I think we should leave it as it is.

I'm happy that you know Kanban, but personally I've never heard it, I see no link to it anywhere, and [the first Google result for Kanban software](https://en.wikipedia.org/wiki/Kanban_%28development%29#Kanban_board_example) distinguishes "ready for development" (which comes after "Specification") and "ready for deployment" (which for a developer is just "ready" tout court). I still trust you that this might be clear to some Kanban subcommunity.

On the one hand, I don't see a problem with "specified", it's even coherent with the rest of the Kanban methodology.

I'm right now realizing how much damage the bad design and naming for `PartialFunction` is. What I learned is something which is probably natural to usability experts:

If a name is prone to misunderstanding (even slightly), change it, rather than requiring people to learn a more complex concept.

(Of course, "more complex" is relative to a target audience).

In fact, unnatural terminology increases the entry barrier to a project. I don't want to go that far, but you could argue that it goes against diversity/inclusiveness and (in the limit) the spirit of a good CoC. (Not the case here, but that's an accurate description of some bad academic English).

**Comment by propensive** [comment]
I was actually going to say that if it's "standard terminology" that's
fine, and we should just leave it to stand. But given Paulo is now the
third person to be confused by it...

Does anyone know if we actually have the ability to change the name? If we
don't, then there's not much point discussing it... ;)

On 28 October 2014 21:04, Paolo G. Giarrusso notifications@github.com
wrote:

> @propensive https://github.com/propensive: +1
> 
> "Ready" is pretty standard Kanban terminology ... I think we should leave
> it as it is.
> 
> I'm happy that you know Kanban, but personally I've never heard it, I see
> no link to it anywhere, and the first Google result for Kanban software
> https://en.wikipedia.org/wiki/Kanban_(development)#Kanban_board_example
> distinguishes "ready for development" (which comes after "Specification")
> and "ready for deployment" (which for a developer is just "ready" tout
> court). I still trust you that this might be clear to some Kanban
> subcommunity.
> 
> On the one hand, I don't see a problem with "specified", it's even
> coherent with the rest of the Kanban methodology.
> 
> I'm right now realizing how much damage the bad design and naming for
> PartialFunction is. What I learned is something which is probably natural
> to usability experts:
> 
> If a name is prone to misunderstanding (even slightly), change it, rather
> than requiring people to learn a more complex concept.
> 
> (Of course, "more complex" is relative to a target audience).
> 
> In fact, unnatural terminology increases the entry barrier to a project. I
> don't want to go that far, but you could argue that it goes against
> diversity/inclusiveness and (in the limit) the spirit of a good CoC. (Not
> the case here, but that's an accurate description of some bad academic
> English).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/typelevel/scala/issues/37#issuecomment-60831241.

## 

Jon Pretty | @propensive

**Comment by milessabin** [comment]
Yes, it could be changed. But are you looking at the [board](https://waffle.io/typelevel/scala)? The flow backlog -> ready -> in progress -> done seems pretty natural.

**Comment by kryptt** [comment]
"avail" / "available"?

Backlog -> available -> in progress - > done?

**Comment by propensive** [comment]
It makes sense on the board, because of its position, but it doesn't make
sense here

   https://github.com/typelevel/scala/issues/51

because you don't have the positional context.

Cheers,
Jon

On 28 October 2014 21:41, Miles Sabin notifications@github.com wrote:

> Yes, it could be changed. But are you looking at the board
> https://waffle.io/typelevel/scala? The flow backlog -> ready -> in
> progress -> done seems pretty natural.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/typelevel/scala/issues/37#issuecomment-60836681.

## 

Jon Pretty | @propensive

**Comment by ebruchez** [comment]
Github tags don't have to be single words, AND can be renamed. You could be explicit and go with something like `Ready to be worked on`. Confusion cleared.

**Comment by ebruchez** [comment]
I just read [Proof in Functions](http://www.fewbutripe.com/swift/math/2015/01/06/proof-in-functions.html) which along the way introduces the idea of typed holes.

Excuse my near-complete ignorance of the topic, but is the idea to have the compiler help/suggest completions, as shown in the GHC link of the OP, or could the compiler even compile a hole into actual code when there is no ambiguity?

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
