### ISSUE TITLE
SI-8519: collection.immutable.Map.apply is inefficient

### ISSUE THREAD

**Issue by fommil** [typelevel/scala#38]
I'm interested in helping out with https://issues.scala-lang.org/browse/SI-8519

**Comment by Blaisorblade** [comment]
I think the fix could go to Typesafe Scala (and would end up here, too, through merging); but if you prefer to work on it in this community, I'm not against it!

**Comment by milessabin** [comment]
:+1:

**Comment by fommil** [comment]
@Blaisorblade Jason said it wasn't so black and white thanks to some awesome third party extension of the collections API (somebody said offline that this was in Eclipse): https://groups.google.com/d/msg/scala-user/WV-3xN8eRQE/cpTHqlie-B4J

**Comment by Blaisorblade** [comment]
@fommil Aah thanks, I see. Are the current deprecations enough?

But
(a) is Typelevel forking the standard library? I thought not.
(b) can we act on deprecations faster, somehow?

I think we all want the answers to be yes, somehow, but we didn't yet. Since 2.12 is not even dropping deprecated methods, I think we might want to open a sort of "2.13 branch" which can change the API. (2.13 is maybe not the best name, but I'll just assume we can find a good name later).

IIRC, we can add deprecations in the 2.11 series (with some techniques to keep compatibility for `-Xfatal-warnings`).

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
