### ISSUE TITLE
Semantics less hostile to optimizations

### ISSUE THREAD

**Issue by Blaisorblade** [typelevel/scala#39]
I know this might be out-of-scope, but Scala's semantics are really hostile to optimizations.

Quoting myself at [Lambda the Ultimate](http://lambda-the-ultimate.org/node/5034#comment-82228):

> [Scala] does not have a well-enough working inliner, which means that lots of functional coding practices have a much bigger cost than in other functional languages. But also, since everything can be compared by identity, it's not even valid to rewrite `a :: Nil map identity` to `a :: Nil` (this is just one example).

What's worse, this affects the compiler codebase itself.

Incidentally, a parametric Scala (Scalazzi?) would avoid that problem.

**Comment by Blaisorblade** [comment]
> Incidentally, a parametric Scala (Scalazzi?) would avoid that problem.

See #40 on that.

**Comment by soc** [comment]
I agree with you, but I'm kind of wondering whether the reasoning "we can't optimize `list map identity` because it needs to return a completely fresh list" actually every existed as a non-strawman.

Was there ever some documentation or explanation why the documentation was written this way, apart from "we wrote it with mutability in mind and forgot to write a better description for immutable collections"?

Imho, it would make sense to just update the ScalaDoc and allow such optimizations. (I don't remember that anyone ever complained that calling `toSet` on a `Set` returned the same set, and this issue is very similar.)

**Comment by Blaisorblade** [comment]
Good question. All domain-specific optimizers I know support these optims.
But here I was thinking about a general-purpose optimizer in Scalac, which can't change the semantics at all because it does not know the library, so it doesn't know which changes are allowed by the documentation. There are certainly objects where identity _is_ important. Maybe ListBuffer already gives an example.
Admittedly, the example I gave seems bad for a different reason: I didn't explain how to prove automatically, in a general-purpose optimizer, that the optimization is otherwise valid. GHC allows for user-specified rewrite rules for this, which could be worth exploring and would avoid the problem.

**Comment by Blaisorblade** [comment]
But the ScalaDoc should probably be checked (and possibly updated) anyway, just so that optimizations docs by e.g. macros are valid.
See also mapConserve.

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
