### ISSUE TITLE
New annotation to force exhaustiveness in match expressions, partial functions and catch blocks

### ISSUE THREAD

**Issue by jchayat** [typelevel/scala#77]
Currently, the Scala compiler emits a warning if cases in a match statement do not form an exhaustive match of a sealed type. In certain situations it would be beneficial to make this an error.

I propose the @exhaustive annotation for match expressions.
I also propose that this works for partial functions and catch blocks as well - forcing the function or block to cover all possible cases.
In addition, I think that this should work for non sealed types as well, by requiring a catch all case .

``` scala
sealed abstract trait A

class B extends A

class C extends A

abstract class E

class F extends E

object X {
  def foo(a: A) = (a: @exhaustive) match {
    case b: B => "hello"
    case c: C => "world"
    // now if someone adds a D extending A an error would arise - alerting the programmer
  }

  val pf: PartialFunction[A, String] = @exhaustive {
    case b: B => "hello"
    case c: C => "world"
  } 

  def bar(e: E) = (e: @exhaustive) match {
    case f: F => "YO!"
    case other => "Hey!" //required!
  }

  def baz = try {
    1 / 0
  } @exhaustive catch {
    case n: NoSuchElementException => 9
    case e => 7 //Required so that all exceptions would be caught
  }

}
```

**Comment by paulp** [comment]
While you're at it you can rename "unchecked", which is ambiguous to the point of meaningless, to "nonexhaustive".

**Comment by paulp** [comment]
By the way, put your code between triple backticks so it looks like code and not a mishmash of text.

**Comment by jchayat** [comment]
@paulp Thanks for the tip!

**Comment by cvogt** [comment]
+1 correctness FTW. Warnings slip through too easily in practice with incremental compilation.

**Comment by aloiscochard** [comment]
I would prefer a flag than an annotation personally.

Do we really want such fine granularity?

**Comment by jchayat** [comment]
@aloiscochard +1 for a flag as well - but IMHO this might be too aggressive - making it an all or nothing issue. In a large project it might be prohibitively costly to fix everywhere, making people stay with the inferior status-quo.
For partial functions a flag makes no sense. Partial function syntax is nice so I would like to avoid having to do

``` scala
val foo: Int => Int = x => x match {
  case 1 => 10
  case 2 => 20
}
```

and do this instead:

``` scala
val foo: Int => Int = @exhaustive {
  case 1 => 10
  case 2 => 20
}
```

**Comment by Blaisorblade** [comment]
:+1: on being able to force these errors.

But I'd separate discussion on catch blocks: catching `Throwable` is usually a bad idea (since it includes `Error`), so that if you do that you get a useful warning (unless you specify `Throwable` explicitly because you really want it). If you always want to catch all non-fatal exceptions, you might be better off abstracting over that (with something like `Try`) — enforcing that _in the compiler_ seems risky (why should Scalac know which exceptions are fatal and which aren't?).

Also, since `Throwable` is not sealed, you can't check exhaustivity for exceptions beyond "there's a catch-all case", so you're left annotating each match to remind yourself to add a catch-all. Is there a point left that I'm missing? If you want support for this case, I think it should be different (not sure how).

> Do we really want such fine granularity?

I think yes.
Idris does the same: you can enable/disable totality checking for each function. One reason, though, is that some functions are total in non-obvious ways. (That's more often a problem for checking that recursion is terminating, but sometimes exhaustiveness is also a problem).

To see why checking exhaustiveness can be hard, consider GADTs. The following code is correct, but will Scalac figure? (In this case, yes). What about more complicated examples? (Protip: no, you can't trust Scalac on GADTs, and I don't think the problem is in general even decidable once you involve type functions).

``` scala
sealed trait Exp[T]
case class Const[T](t: T) extends Exp[T]
case class Pair[A, B](a: Exp[A], b: Exp[B]) extends Exp[(A, B)]
def f(e: Exp[Int]): Int = (e: @exhaustive) match {
  case Const(t) => t
}
```

So, I'd often need the annotation. Even more often, I'd like the flag _and_ an annotation to shut up the compiler (`@unchecked` or `@nonexhaustive`) in the exceptional cases (hoping they're a minority, or that I want to review every error, including false positives).

**Comment by paulp** [comment]
>  enforcing that in the compiler seems risky (why should Scalac know which exceptions are fatal and which aren't?).

One could as well ask why should the library - since it doesn't know, at all, and cannot. I already had to rewrite that wrapper to exclude a different set of exceptions.

**Comment by Blaisorblade** [comment]
> One could as well ask why should the library - since it doesn't know, at all, and cannot. I already had to rewrite that wrapper to exclude a different set of exceptions.

OK, but that part is just _a_ library — you can write another one even without forking the compiler :-). (I know parts of the stdlib are special, but IIRC/hopefully not this one).
Assuming that choice is useful to some people (EDIT: count me in), whether `Try` belongs in _a_ library or _the library_ is a question I won't tackle myself.

What's sad is that `Try` does not offer an overridable extension point for changing exceptions, because it inlines the following `bracket` method 7 times:
`def bracket[T](t: => Try[T]): Try[T] = try t catch { case NonFatal(e) => Failure(e) }`
One can deinline it, modulo SI-4440 (haven't tried working it around). Something like https://gist.github.com/Blaisorblade/514499b9993c8f337ab3, probably with a better specification of what's expected from `bracket` implementations.

**Comment by Blaisorblade** [comment]
(On reflection, [`NonFatal.apply`](https://github.com/scala/scala/blob/2.11.x/src/library/scala/util/control/NonFatal.scala#L35) is likely a better extension point).

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
