### ISSUE TITLE
Return types of dependently-typed methods on stable identifiers should get dealiased

### ISSUE THREAD

**Issue by propensive** [typelevel/scala#84]
Compare the return types of `f.foo` and `g.foo`.

```
scala> trait Foo { type T; def foo: T = null.asInstanceOf[T] }
defined trait Foo

scala> val f = new Foo { type T = String }
f: Foo{type T = String} = $anon$1@10e80317

scala> f.foo
res0: f.T = null

scala> def g = new Foo { type T = String }
g: Foo{type T = String}

scala> g.foo
res1: String = null
```

I don't believe that returning the path-dependent type is ever preferable over returning the dealiased type, though I might be wrong.

**Comment by propensive** [comment]
Particularly interested in thoughts from @milessabin and @folone on this one, as it affects singleton types.

**Comment by Blaisorblade** [comment]
Let's see if I understand what you're showing: since `g` is a method and thus unstable, `g.foo`'s return type must be dealiased because you can't even say `g.T`. That's not needed for the value `f` (which is stable), which gives rise to a difference.

However, those two types are (supposedly) equal, so supposedly it can't make a difference (citation: vObj paper); if you can find a context where the two have a difference, the handling of that context must be fixed. I think I saw multiple such bugs in Scalac's bug tracker.

Type inference comes to mind. However, it manages to dealias things OK enough — it's harder to realias thing if you dealias too early, as [@retronym explained me](https://github.com/scala/scala/pull/3979#issuecomment-55840971).

> Let's say the type checker dealiased the type of every term after typechecking. One thing we'd notice is that attempts to use type aliases to adapt the arity of type constructors could no longer influence type constructor inference: [...omitted example...]

So, we can combine his example with yours to show an example which your proposed change would break:

``` scala
scala> class A
defined class A

scala> trait Foo { type Unary[_] = A; def foo: Unary[String] = null.asInstanceOf[Unary[String]] }
defined trait Foo

scala> def foo[M[_], A](m: M[A]): M[String] = ???
warning: there were 1 feature warning(s); re-run with -feature for details
foo: [M[_], A](m: M[A])M[String]

scala> val f = new Foo {};
f: Foo = $anon$1@287cbb10

scala> def x = foo(f.foo)
x: f.Unary[String]

scala> def x1 = foo(f.foo: A)
<console>:11: error: no type parameters for method foo: (m: M[A])M[String] exist so that it can be applied to arguments (A)
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : A
 required: ?M[?A]
       def x1 = foo(f.foo: A)
                ^
<console>:11: error: type mismatch;
 found   : A(in object $iw)
 required: M[A(in method foo)]
       def x1 = foo(f.foo: A)
                         ^
```

Earlier failed attempts at breaking things (not sure anybody should care).

``` scala
scala> val f = new Foo { type T = List[Int] }; f.foo
f: Foo{type T = List[Int]} = $anon$1@4af2d44c
res1: f.T = null

scala> def h[L[_], A](x: L[A]) = x
warning: there were 1 feature warning(s); re-run with -feature for details
h: [L[_], A](x: L[A])L[A]

scala> h(f.foo)
res2: List[Int] = null

scala> def h[L[_] <: AnyRef, A](x: L[A]): x.type = x
warning: there were 1 feature warning(s); re-run with -feature for details
h: [L[_] <: AnyRef, A](x: L[A])x.type

scala> h(f.foo)
res3: f.T = null

scala> def bar = { val f = new Foo { type T = String }; f.foo }
bar: String
```

**Comment by Blaisorblade** [comment]
In #84 you write:

>  I often use defs just to avoid this issue -- despite the additional object creation

so it sounds like you did run into some issue. But which is it?

**Comment by milessabin** [comment]
To resurrect this issue, please rework it as an issue/PR against Lightbend Scala (ie. scala/scala).
